### ISSUE TITLE
PaperSpigot vs. GlowAPI

### ISSUE THREAD

**Issue by CeIebrimbor** [InventivetalentDev/GlowAPI#1]
Console:
`22.06 22:28:00 [Server] WARN [ReflectionHelper] Failed to find DataWatcherObject for Entity #57 
22.06 22:28:00 [Server] WARN [ReflectionHelper] Failed to find DataWatcherObject for Entity #58 
22.06 22:28:00 [Server] ERROR java.lang.NullPointerException 22.06 22:28:00 [Disconnect] User CeIebrimbor has disconnected, reason: Disconnected`

This was discussed on Spigot page for GlowAPI as being a conflict with PaperSpigot.

**Comment by InventivetalentDev** [comment]
What server version are you on?

**Comment by InventivetalentDev** [comment]
Fixed in [ReflectionHelper v1.10.1](https://www.spigotmc.org/resources/api-reflectionhelper-1-7-1-8-1-9-1-10.19241/update?update=101149) / [GlowAPI v1.4.4](https://www.spigotmc.org/resources/api-glowapi-1-9-1-10.19422/update?update=101152).
