### ISSUE TITLE
1.5.2-SNAPSHOT not accessible from maven 

### ISSUE THREAD

**Issue by DrevitWeb** [InventivetalentDev/GlowAPI#108]
I wanted to add dependency on my maven plugin with 

```
        <dependency>
            <groupId>com.github.InventivetalentDev</groupId>
            <artifactId>GlowAPI</artifactId>
            <version>1.5.1-SNAPSHOT</version>
        </dependency>
```

and 

```
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
```

and I can't found version, my maven says not existing

**Comment by Sebastian-Sole** [comment]
Same thing happens to me with 1.5.2-SNAPSHOT

**Comment by InventivetalentDev** [comment]
build keeps timing out, no idea why 🤷 https://jitpack.io/org/inventivetalent/GlowAPI/1.5.2-SNAPSHOT/build.log  
don't really have time to try and debug that atm

**Comment by celciusjj** [comment]
same case
