### ISSUE TITLE
The plugin is not working with 1.13

### ISSUE THREAD

**Issue by IzzyKap** [InventivetalentDev/GlowAPI#12]
## What steps will reproduce the problem?  
1. Install the plugin
2. Run the server on 1.13

## What were you expecting to happen? What happened instead?  
The plugin to load given that 1.13 was supposed to have legacy plugin support

## What Spigot version are you using? *Type /version*  
This server is running CraftBukkit version git-Spigot-0b44fa0-1ef1ffd (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

## What plugins ae you using? *Type /plugins*  
GlowAPI version 1.4.6-SNAPSHOT

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/5axYGkT4

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
It disconnected from the server but did not crash

**Comment by InventivetalentDev** [comment]
> 1.13 was supposed to have legacy plugin support
pretty sure that only goes for plugins that don't mess with the protocol, as i.e. this plugin does  

I won't be at home for the next few weeks, so not sure how quick I can update the API.

**Comment by IzzyKap** [comment]
That is fine, whenever you get to it. A magic plugin I made used it but I
set it to check if the plugin is installed and if it's not than just do
nothing when the glow function is called so I'm good to wait. Thank you for
updating whenever you get to it.

**Comment by SydMontague** [comment]
So, because I stumbled upon the same problem I took a deeper look into the issue and what would be necessary for it to fix it.

It seems like the PacketPlayOutScoreboardTeam class got changed to use ChatComponentText instead for String for display name, prefix and suffix as well as EnumChatFormat instead of int for the color.

I compiled a patch for it, so feel free to use that if it's useful for you. It should break <1.13 compatibility due to the protocol change, though.
[1.13fix.patch.txt](https://github.com/InventivetalentDev/GlowAPI/files/2250811/1.13fix.patch.txt)

**Comment by IzzyKap** [comment]
Thanks, would you possibly be able to send me a copy of the jar compiled
with that patch to load on my server? My computer is in the shop and I
don't think I can explain to any of my staff how to compile stuff.

**Comment by SydMontague** [comment]
You should use it with caution, it's not an official release, not properly tested and definitely not supported...

[GlowAPI_v1.4.7-CUSTOM-SNAPSHOT.zip](https://github.com/InventivetalentDev/GlowAPI/files/2251027/GlowAPI_v1.4.7-CUSTOM-SNAPSHOT.zip)

**Comment by IzzyKap** [comment]
It had an error when running: Anyways thanks for setting it up, worst comes
to worst I'll just wait for the official version and disable the glow part
of my magic plugin for now. If it's to much trouble don't worry about it,
thanks for trying.

01.08 16:55:30 [Server] WARN java.lang.IllegalArgumentException: wrong
number of arguments 01.08 16:55:30 [Server] WARN at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method) 01.08 16:55:30 [Server] WARN at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01.08 16:55:30 [Server] WARN at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01.08 16:55:30 [Server] WARN at
java.base/java.lang.reflect.Method.invoke(Method.java:564) 01.08 16:55:30
[Server] WARN at
org.inventivetalent.glow.GlowAPI$Color.<init>(GlowAPI.java:429) 01.08
16:55:30 [Server] WARN at
org.inventivetalent.glow.GlowAPI$Color.<clinit>(GlowAPI.java:402) 01.08
16:55:30 [Server] WARN at
org.inventivetalent.glow.GlowAPI.initTeam(GlowAPI.java:319) 01.08 16:55:30
[Server] WARN at
org.inventivetalent.glow.GlowAPI.initTeam(GlowAPI.java:330) 01.08 16:55:30
[Server] WARN at
org.inventivetalent.glow.GlowAPI.onJoin(GlowAPI.java:523) 01.08
16:55:30 [Server] WARN at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method) 01.08 16:55:30 [Server] WARN at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01.08 16:55:30 [Server] WARN at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01.08 16:55:30 [Server] WARN at
java.base/java.lang.reflect.Method.invoke(Method.java:564) 01.08 16:55:30
[Server] WARN at
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
01.08 16:55:30 [Server] WARN at
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
01.08
16:55:30 [Server] WARN at
org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
01.08 16:55:30 [Server] WARN at
org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
01.08 16:55:30 [Server] WARN at
net.minecraft.server.v1_13_R1.PlayerList.onPlayerJoin(PlayerList.java:343)
01.08
16:55:30 [Server] WARN at
net.minecraft.server.v1_13_R1.PlayerList.a(PlayerList.java:163) 01.08
16:55:30 [Server] WARN at
protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:134)
01.08 16:55:30 [Server] WARN at
protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:123)
01.08 16:55:30 [Server] WARN at
protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tick(AbstractLoginListenerPlay.java:85)
01.08 16:55:30 [Server] WARN at
protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.Y_(SpigotLoginListenerPlay.java:80)
01.08 16:55:30 [Server] WARN at
net.minecraft.server.v1_13_R1.NetworkManager.a(NetworkManager.java:231) 01.08
16:55:30 [Server] WARN at
net.minecraft.server.v1_13_R1.ServerConnection.c(ServerConnection.java:120)
01.08
16:55:30 [Server] WARN at
net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:984) 01.08
16:55:30 [Server] WARN at
net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) 01.08
16:55:30 [Server] WARN at
net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819)

**Comment by InventivetalentDev** [comment]
@SydMontague please create a pull request if your changes fix the issues!

**Comment by TheIntelloBox** [comment]
Any update ?
