### ISSUE TITLE
Glow goes away

### ISSUE THREAD

**Issue by TherealB9B** [InventivetalentDev/GlowAPI#126]
**Describe the bug**
When shifting or sprinting the glow effect goes away.
( Im using mythicmobs, this skill - effect:glow{color=AQUA;duration=600} @PetOwner ~onTimer:1900
**To Reproduce**
1. Give someone the glow effect.
2. let them crouch/sprint

**Expected behavior**
The effect stays until the timer runs out.

**Screenshots**
https://gyazo.com/33cff1db7cd226a076eef39a525407fb)

**Additional context**
I'm using a mythicmobs skill but I don't think thats causing this.
Using glowapi 1.5.4
Using packetlistener 3.9.10.

**Comment by srnyx** [comment]
This is happening to me too, @InventivetalentDev please fix!

**Comment by TherealB9B** [comment]
> This is happening to me too, @InventivetalentDev please fix! _I'm not using MythicMobs._

I don't think it will be fixed, or the dev is very busy because i reported the bug almost a month ago

**Comment by srnyx** [comment]
> I don't think it will be fixed, or the dev is very busy because i reported the bug almost a month ago

Do you know of another glow API I could use?

**Comment by InventivetalentDev** [comment]
until I get a chance to look into this, you can probably just listen to crouch events etc. and re-apply the glow

**Comment by srnyx** [comment]
> until I get a chance to look into this, you can probably just listen to crouch events etc. and re-apply the glow

That's what I had (for other reasons) but it still didn't stay.

**Comment by iHDeveloper** [comment]
> > until I get a chance to look into this, you can probably just listen to crouch events etc. and re-apply the glow
> 
> That's what I had (for other reasons) but it still didn't stay.

I asked @InventivetalentDev to have the chance to try to fix this issue.

@srnyx @TherealB9B May I ask which Minecraft verison are you both referring to? And does that include`1.18+`?

**Comment by srnyx** [comment]
> @srnyx @TherealB9B May I ask which Minecraft verison are you both referring to? And does that include`1.18+`?

I'm using 1.19.2 with `git-Purpur-1754`.

**Comment by TherealB9B** [comment]
> I asked @InventivetalentDev to have the chance to try to fix this issue.
> 
> @srnyx @TherealB9B May I ask which Minecraft verison are you both referring to? And does that include`1.18+`?
> 
> > > until I get a chance to look into this, you can probably just listen to crouch events etc. and re-apply the glow
> > 
> > 
> > That's what I had (for other reasons) but it still didn't stay.
> 
> I hope this is not a client side issue. I'm gonna investigate this.

I was using 1.19 or 1.19.2

**Comment by srnyx** [comment]
@TherealB9B This was fixed btw
