### ISSUE TITLE
Glow does not appear if receiver is not close to entity

### ISSUE THREAD

**Issue by srnyx** [InventivetalentDev/GlowAPI#128]
**Describe the bug**
When glow is applied to an entity, players that don't have the entity rendered, won't see its glow when their client renders it.

**To Reproduce**
1. Give an entity glowing with it unrendered on the client
2. Walk up to it so that it's rendered
3. It won't be glowing

**Expected behavior**
The entity should be glowing

**Screenshots**
![image](https://user-images.githubusercontent.com/25808801/187114480-5ef05275-39fc-44d1-a455-83f32faca02a.png)

**Possible solutions**
1. You could apply the glow every once in a while (either in the API or on my side)
2. Find another way around this (not sure how packets entirely work)

**Comment by iHDeveloper** [comment]
Thank you for reporting the issue! We appreciate it :)

I'm wondering, Which Minecraft versions you tried produced the issue?

> You could apply the glow every once in a while (either in the API or on my side)
I agree with you, that would work as a temporary solution.

> Find another way around this (not sure how packets entirely work)
I referenced this issue in an already open pull request, that purposes a solution at the packet, Nice prediction of a possilbe way with packets. :)

**Comment by srnyx** [comment]
> I'm wondering, Which Minecraft versions you tried produced the issue?

1.19.2
