### ISSUE TITLE
Glowing on Player are not working with Optifine.

### ISSUE THREAD

**Issue by x9nico** [InventivetalentDev/GlowAPI#19]
## What steps will reproduce the problem?  
1. Run the server
2. Create a plugin with the example on Spigot Page
3. Connect to the Server

## What were you expecting to happen? What happened instead?  

The Glowing are not working.

![image](https://user-images.githubusercontent.com/8091015/60382979-6ea50f00-9a6b-11e9-991f-5c3b8828b4d4.png)

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  

Latest: 1.4.8-SNAPSHOT

## What Spigot version are you using? *Type /version*  
![image](https://user-images.githubusercontent.com/8091015/60382945-e0c92400-9a6a-11e9-9a92-3ddf1d0f21e3.png)

## What plugins ae you using? *Type /plugins*  
GlowAPI, PacketListenerAPI, and my plugins with the Spigot example

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  

No errors.

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  

No.

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*

In previous versions, it is not work to.

**Comment by InventivetalentDev** [comment]
Is the completely red texture in the image your player's skin?  
If it's not, it's likely that you're using optifine which often creates an overlay of the glow color instead of the usual outlines.

**Comment by x9nico** [comment]
Yeah, it does that when we have Optifine.
Can you do something for fix with Optifine please ?

**Comment by InventivetalentDev** [comment]
Uhm, no...   
Optifine is a client-side modification. That's something they will have to fix.  
Nothing I can do about it.
