### ISSUE TITLE
1.14.4 Console Spam

### ISSUE THREAD

**Issue by CarsonJF** [InventivetalentDev/GlowAPI#22]
1. Running the newest dev version of glowapi spams errors in console on paper 1.14.4

running glowapi 1.4.8 dev generates so many errors in console when a player has a glowing item that it crashes server.

Paper(135) 1.14.4-R0.1-Snapshot

**Comment by CarsonJF** [comment]
UPDATE:

https://pastebin.com/xhkaujgu

Glow itself works, but no color, and console spam when glow enables on item.

GlowAPI - 1.4.9 Dev Snapshot
Paper (135) 1.14.4-R0.1-SNAPSHOT

**Comment by InventivetalentDev** [comment]
Please give the 1.4.10 snapshot a try, it should get the proper field.

**Comment by CarsonJF** [comment]
No errors, and colors are working properly again :) Thank you!
