### ISSUE TITLE
Errors with GlowAPI on 1.14.4

### ISSUE THREAD

**Issue by Kichiro72** [InventivetalentDev/GlowAPI#27]
## What steps will reproduce the problem?  
1. spawn mob with glow effect
2. got mob glow only white color and errors in console

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
GlowAPI_v1.4.10-SNAPSHOT.jar

## What Spigot version are you using? *Type /version* 
Spigot 1.14.4 

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/7MhT19bt

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
no

**Comment by TheSteveRizzo** [comment]
Also having this error.

**Comment by Skeagle137** [comment]
> Also having this error.

Still happening in 1.15.2 as well.

**Comment by InventivetalentDev** [comment]
Likely caused by using Spigot instead of Paper. Please try switching to that until I can add a workaround for this.

**Comment by Skeagle137** [comment]
> Likely caused by using Spigot instead of Paper. Please try switching to that until I can add a workaround for this.

Thanks, that fixes it
