### ISSUE TITLE
Console error paper 233 1.14.4

### ISSUE THREAD

**Issue by TheAncientDragon** [InventivetalentDev/GlowAPI#29]
## What steps will reproduce the problem?  
add the plugin to plugins folder and run the server

## What were you expecting to happen? What happened instead?  
expecting it to load properly and it is giving me a console error

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.14.10 snapshot

## What Spigot version are you using? *Type /version*  
using paper instead, 233

## What plugins ae you using? *Type /plugins*  
[13:13:48 INFO]: Plugins (17): AsyncWorldEdit, EffectLib*, Heroes, HolographicDisplays, LuckPerms, MCSSCommunicator, MMOItems, Multiverse-Core*, MythicMobs, PlaceholderAPI, ProtocolLib, Realistic_World, Vault, VoidGenerator, Votifier, WorldEdit, WorldGuard

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/7n6dGXJA

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
no
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
i remember it was working and dont remember what i did, maybe adding another plugin.

**Comment by metalshark** [comment]
@TheAncientDragon installing https://github.com/InventivetalentDev/PacketListenerAPI/releases fixed this for me.
