### ISSUE TITLE
JoinEvent Effect Not Colored.

### ISSUE THREAD

**Issue by bluefutureMC** [InventivetalentDev/GlowAPI#3]
## What steps will reproduce the problem?
1. adding this to my player join event
2. joining with the right perms
## What were you expecting to happen? What happened instead?

i expect that the player will join with colored glow effect but it is not happening
## What version of the plugin are you using? _Type /version &lt;Plugin Name&gt;_

1.4.4
## What Spigot version are you using? _Type /version_

Spigot-9797151-301db84 minecraft 1.10.2
## What plugins are you using? _Type /plugins_

GlowAPI, PacketListenerAPI, Pex (and of course my plugin)
## Do you have an error log? Use [pastebin.com](http://pastebin.com). _If you're not sure, upload your whole server log_

No Errors!
## Did your client crash? _Upload errors in .minecraft/logs/latest.log as well_

No.
## Additional information?  _(Are you using Bungeecord? Did it work in previous versions? etc.)_

my code: http://pastebin.com/23KBST8M

**Comment by InventivetalentDev** [comment]
Please check what _#getGlowColor_ returns for the player.
You might also have to use a few ticks delay since you're doing this right when the player joins.
