### ISSUE TITLE
Blink glowing effect

### ISSUE THREAD

**Issue by ghost** [InventivetalentDev/GlowAPI#4]
## What steps will reproduce the problem?
1. Add glowing effect view to specific players
2. Do an animation with a player who has the glowing effect (Sprinting or crouching)
## What were you expecting to happen? What happened instead?

What were you expecting to happen: The players without the permission can't see the glowing effect on other players.
What happened instead: But when a player with the glowing effect do an animation, it shows for everyone (well like a glitch, it blink with the color white (event if this is another color)
## What version of the plugin are you using? _Type /version &lt;Plugin Name&gt;_

GlowAPI Version 1.4.4
PacketListenerAPI Version 3.4.4
## What Spigot version are you using? _Type /version_

Version 1.10.2-R0.1-SNAPSHOT
## What plugins are you using? _Type /plugins_

Custom Plugins, GlowAPI, PacketListnersAPI, Citizens
## Do you have an error log? Use [pastebin.com](http://pastebin.com). _If you're not sure, upload your whole server log_

No error in the server LOG
## Did your client crash? _Upload errors in .minecraft/logs/latest.log as well_

No 
## Additional information?  _(Are you using Bungeecord? Did it work in previous versions? etc.)_

N/A

**Comment by InventivetalentDev** [comment]
So, the problem is that players you don't want to see the glow? (The API doesn't do stuff with permissions, so I guess that's what your custom plugin does) 
Please post the code you use the apply the effect.

**Comment by Khashan** [comment]
Code: http://pastebin.com/Uez7T8TC

Yeah everything works, but what I mean is when the WrappedDataWatcher changes because the player has sprinted or crouched, the glowing effect start to blink and everyone in the server can see that.
