### ISSUE TITLE
The glow color is white, but not the color I set ...

### ISSUE THREAD

**Issue by Pyario** [InventivetalentDev/GlowAPI#44]
## What steps will reproduce the problem?  
1. I don't now.
2.
3. 

## What were you expecting to happen? What happened instead?  

 - The glow color is white, but not the color I set ...

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  

GlowAPI - 1.4.11-Snapshot

## What Spigot version are you using? *Type /version*  

- Paper-176 | 1.15.2

## What plugins ae you using? *Type /plugins*  

GlowAPi, PackListenerAPI, And my Own plugin :D

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  

No, errors.

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  

No.

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*

I don't test previous versions. |  Bungeecord no.

P.s: My Code:

`Bukkit.getScheduler().scheduleSyncRepeatingTask(pl, new Runnable() {
                            @Override
                            public void run() {
                                GlowAPI.setGlowing(p, GlowAPI.Color.PURPLE, Bukkit.getOnlinePlayers());
                            }
                        },0,20);
`

I don't know if there is a problem with 1.15.2! But will probably be.

Best Regards,

Pyario

**Comment by TUCAOEVER** [comment]
i found that issue too
