### ISSUE TITLE
Glow Effect Displays for all players

### ISSUE THREAD

**Issue by GamerBah** [InventivetalentDev/GlowAPI#5]
## What steps will reproduce the problem?
1.  Apply the Glow Effect to 2 different players
## What were you expecting to happen? What happened instead?

Expected that only the 2 defined players would see the glow effect, but anyone can see it.
## What version of the plugin are you using? _Type /version &lt;Plugin Name&gt;_

1.4.4
## What Spigot version are you using? _Type /version_

1.9.4
## What plugins ae you using? _Type /plugins_

MinecraftMarket, TitleAPI, PacketListenerAPI, WorldEdit, Ram_Monitor (hosting thing), TabListAPI, VoxelSniper, ParticleLIB, GlowAPI, Vault, ConsoleSpamFix, PlayerVersion, Battlegrounds (custom)
## Do you have an error log? Use [pastebin.com](http://pastebin.com). _If you're not sure, upload your whole server log_

No errors
## Did your client crash? _Upload errors in .minecraft/logs/latest.log as well_

No
## Additional information?  _(Are you using Bungeecord? Did it work in previous versions? etc.)_

Here's the code where I set the glowing effect: http://pastebin.com/0KWUcNGY
I set the glowing effect for 2 players, however, everyone can see the effect

**Comment by StevasaurousREX** [comment]
Paste is private, but I assume you used 'Bukkit.getOnlinePlayers()' for your collection to display the color too or something similar that includes all the players. You probably want
```
public static void setGlowing(org.bukkit.entity.Entity entity,
                              boolean glowing,
                              org.bukkit.entity.Player receiver)
```
If this is what you do sorry the paste is private, just trying to help.
