### ISSUE TITLE
Possible to retain prefix/suffix from global scoreboard?

### ISSUE THREAD

**Issue by RoboMWM** [InventivetalentDev/GlowAPI#7]
Seems this plugin (testing with [uGlow](https://www.spigotmc.org/resources/uglow-1-10.19520/)) sends an entirely new team/scoreboard to the client for glowing players.

Is it possible you could use the server's scoreboard and only change the team color being sent to clients? I currently use the global scoreboard for various things (health in one plugin, clan prefix in another).

Alternatively (and would be better since it would allow for prefixes/suffixes/etc. to be updated without you having to "re-process"), if it's possible to just send a team color packet, that'd be the best way.

I'm not too familiar with the packet side of things, so not sure if this is feasible. (Otherwise I'll just set team colors myself and apply glow effect when necessary.)

**Comment by RoboMWM** [comment]
I hate this stupid stale bot this has been added to another project that also marked an issue that was scheduled(!!) to be stale!

**Comment by RoboMWM** [comment]
yes this is relevant and what's blocking it is if this is desired but at this point idk if I even care that much anymore

**Comment by InventivetalentDev** [comment]
don't really have plans changing how this sends glow colors, sorry.
