### ISSUE TITLE
[BUG] Spigot 1.16.2 compatibility

### ISSUE THREAD

**Issue by LoneDev6** [InventivetalentDev/GlowAPI#71]
## What steps will reproduce the problem?  
1. install spigot 1.16.2
2. use method org.inventivetalent.glow.GlowAPI.setGlowing()

## What were you expecting to happen? What happened instead?  
no error

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
GlowAPI version 1.4.10-SNAPSHOT

## What Spigot version are you using? *Type /version*  
This server is running CraftBukkit version git-Spigot-379750e-fe4efd1 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

## What plugins ae you using? *Type /plugins*  
100+ plugins

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/YFDGX1BN

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
no

Probably this would work with Paper as the package "it.unimi.dsi.fastutil.ints" is only available on Paper.
Spigot has this package: "org.bukkit.craftbukkit.libs.it.unimi.dsi.fastutil.ints"

**Comment by GuerreroCraft61** [comment]
In 1.16.1: https://gist.github.com/GuerreroCraft61/8db18e729352644b6f5baa42f3d4c1b9
