### ISSUE TITLE
GlowAPI

### ISSUE THREAD

**Issue by GTBelo** [InventivetalentDev/GlowAPI#72]
## What steps will reproduce the problem?  

1. Install GlowAPI

2. Install TacoSpigot

## What were you expecting to happen? What happened instead?  
Functioned normally

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  

1.4.13

## What Spigot version are you using? *Type /version*  

TacoSpigot-1.12.2-b114.jar

## What plugins ae you using? *Type /plugins*  

None that interfere

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  

https://pastebin.com/J1Yrn4s0

**Comment by GTBelo** [comment]
Hi?

**Comment by InventivetalentDev** [comment]
o/  
There's likely another error on server startup, please include that too.

**Comment by GTBelo** [comment]
This is the only error on my console:

https://pastebin.com/C8xyS39b

This is my last log:

https://pastebin.pl/view/7dcfc1a6

**Comment by InventivetalentDev** [comment]
Looks like TacoSpigot is probably messing with this.

**Comment by GTBelo** [comment]
Don't you intend to offer compatibility for TacoSpigot?

**Comment by InventivetalentDev** [comment]
Nope. I really don't have the time to support every single fork of spigot/paper, sorry.

**Comment by GTBelo** [comment]
Not even if we make a donation?
