### ISSUE TITLE
Scoreboard teams with colors modify the specified glow color

### ISSUE THREAD

**Issue by JordanOsterberg** [InventivetalentDev/GlowAPI#74]
## What steps will reproduce the problem?  
1. Register a team on the main scoreboard, and set its color to ChatColor.RED
2. Add the player to the team
3. Set the player's glow to blue using the API for all online players

## What were you expecting to happen? What happened instead?  
The player's glow should be blue. The player's glow was red.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.14.13-SNAPSHOT

## What Spigot version are you using? *Type /version*  
1.16.1-R0.1

## What plugins ae you using? *Type /plugins*  
ProtocolLib, PacketListenerApi, GlowAPI, 2 custom plugins which do not interfere or modify packets.

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Using BungeeCord but unsure if this would create this issue.

**Comment by InventivetalentDev** [comment]
Not really much I can do about that, since scoreboard team colors are how MC gets the glow color.

**Comment by JordanOsterberg** [comment]
@InventivetalentDev I figured as much from the source but thought I would at least open an issue in case you weren't aware. Thanks for the update- will use a workaround :]
