### ISSUE TITLE
White Glow Blink after disabling Glow

### ISSUE THREAD

**Issue by OverlordWeaponry** [InventivetalentDev/GlowAPI#75]
## What steps will reproduce the problem?  
1. Apply a glow effect (I used RED) to you and another player
2. After a while, disable the effect.
3. If you walk around, you'll occasionally see you and/or the other player blink white

## What were you expecting to happen? What happened instead?  
When I disabled the glow, I expect that player to no longer glow, but instead there is this weird blink effec going on

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.4.13

## What plugins ae you using? *Type /plugins*  
PacketListenerAPI, ProtocolLib, GlowAPI, WorldGuard, BKCommonLib, LightCleaner

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No.

**Comment by andrei1058** [comment]
I'm having issues with white glowing after removing it from an entity as well.

**Comment by AdiihYT** [comment]
Exactly the same problem is going on with me, when I applied different glow colors to players (it doesn't matter which color), you'll sometimes see you and/or the other players in white glowing effect.
![Screenshot_2](https://user-images.githubusercontent.com/34807024/123636076-b8708d80-d81c-11eb-8df4-6a0d0f100d67.png)
