### ISSUE TITLE
jdk 16 seems to create an issue

### ISSUE THREAD

**Issue by hetile1** [InventivetalentDev/GlowAPI#82]
**Describe the bug**

After updating to java 16, the plugin is now throwing an error:
```Could not pass event PlayerJoinEvent to GlowAPI v1.4.14-SNAPSHOT```

This wasn't an issue on java 14

**To Reproduce**
1. Installl jdk 16
2. Start the server
3. Connect on it

**Expected behavior**
Not throwing an error in the console

**Additional context**
This is a new issue that come with the jdk update forced by paper/upcoming v1.17

Running latest build of paper-mc (#675 at the time of writing this)

**Comment by Korinocho** [comment]
Same here!
