### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by JohnFawkes** [InventivetalentDev/GlowAPI#83]
**Describe the bug**
Plugin doesnt load

**To Reproduce**
1. On latest paper, glowapi and packetlistener

**Additional context**
https://paste.dedimc.io/etiwexegax.md

**Comment by lexikiq** [comment]
failure starts with PaperMC/Paper@cb896d4710c2a827281f701682bbb8e0afff0818, an upstream update commit, meaning this likely occurs on Spigot as well.

**Comment by CodeByCam** [comment]
Experiencing this issue too: https://paste.helpch.at/cerasodebe.rb

Purpur version: `git-Purpur-1149 (MC: 1.16.5)`
PacketListenerApi version: `3.9.1-SNAPSHOT`
GlowAPI version: `1.4.15-SNAPSHOT`

**Comment by Deltazura** [comment]
Same : https://pastebin.com/n7nTeVPP

**Comment by kiloRs** [comment]
Also having this issue!

**Comment by andrei1058** [comment]
Same issue

**Comment by HexedHero** [comment]
Same issue

**Comment by JohnFawkes** [comment]
Closing Issue. fixed in latest version. Thanks
