### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by PixelLima** [InventivetalentDev/GlowAPI#9]
## What steps will reproduce the problem?  
1. Call sendGlowPacket().
2. Call sendTeamPacket().
3. Use setGlowing() for a comparison.

## What were you expecting to happen? What happened instead?  
I expected the plugin to work normally but instead I found out that it behavior is confusing.

## What version of the plugin are you using? 
I am using the 1.4.4 version.

## What Spigot version are you using? 
Spigot 1.10.2

## What plugins are you using? 
One custom plugin to use the API, the GlowAPI and its dependencies

## Do you have an error log? Use [pastebin.com](http://pastebin.com). 
There is no error log on the screen.

## Did your client crash?
The client did not crash.

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Not using BungeeCord.

**Comment by ImSickPT** [comment]
I do not find this problem a priority and I was just looking for an explanation to why this happens.
